package classes;
// Generated 28-abr-2018 13:41:34 by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes", schema="empresa2")
public class Clientes implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "numero")
	private Integer numero;
    @Column(name = "nif", nullable = false, length = 12)
	private String nif;
    @Column(name = "nombre", nullable = false, length = 45)
	private String nombre;
    @Column(name = "direccion", nullable = false, length = 80)
	private String direccion;
    @Column(name = "telefono", nullable = false, length = 15)
	private String telefono;
    @Column(name = "email", nullable = false, length = 45)
	private String email;
    @OneToMany(targetEntity=Facturas.class)
    @JoinColumn(name="numero")
	private Set facturases = new HashSet(0);

	public Clientes() {
	}

	public Clientes(String nif, String nombre, String direccion, String telefono, String email, Set facturases) {
		this.nif = nif;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.email = email;
		this.facturases = facturases;
	}

	public Integer getNumero() {
		return this.numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Set getFacturases() {
		return this.facturases;
	}

	public void setFacturases(Set facturases) {
		this.facturases = facturases;
	}

}
