package classes;
// Generated 28-abr-2018 13:41:34 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facturas generated by hbm2java
 */
@Entity
@Table(name="facturas", schema="empresa2")
public class Facturas implements Serializable {
	
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "numero")//,nullable = false
	private String numero;
	@ManyToOne(cascade = CascadeType.PERSIST)
	@JoinColumn(name="cliente")//antes numero pero me daba error, repeated column
	private Clientes clientes;
	@Column(name = "fecha", nullable = false, length = 45)
	private String fecha;
	@Column(name = "estado", nullable = false, length = 15)
	private String estado;
	@Column(name = "concepto", nullable = false, length = 180)
	private String concepto;
	@Column(name = "total", nullable = false)
	private Float total;
	//se ha modificado el atributo fecha de Date a String 27/04/2018 por warning de DBManagerHibernate

	public Facturas() {
	}

	public Facturas(String numero) {
		this.numero = numero;
	}

	public Facturas(String numero, Clientes clientes, String fecha, String estado, String concepto, Float total) {
		this.numero = numero;
		this.clientes = clientes;
		this.fecha = fecha;
		this.estado = estado;
		this.concepto = concepto;
		this.total = total;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}


}
