package classes;
// Generated 28-abr-2018 13:41:34 by Hibernate Tools 5.3.0.Beta2

import java.util.Date;

/**
 * Facturas generated by hbm2java
 */
public class Facturas implements java.io.Serializable {

	private String numero;
	private Clientes clientes;
	private String fecha;
	private String estado;
	private String concepto;
	private Float total;
	//se ha modificado el atributo fecha de Date a String 27/04/2018 por warning de DBManagerHibernate

	public Facturas() {
	}

	public Facturas(String numero) {
		this.numero = numero;
	}

	public Facturas(String numero, Clientes clientes, String fecha, String estado, String concepto, Float total) {
		this.numero = numero;
		this.clientes = clientes;
		this.fecha = fecha;
		this.estado = estado;
		this.concepto = concepto;
		this.total = total;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public String getFecha() {
		return this.fecha;
	}

	public void setFecha(String fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public Float getTotal() {
		return this.total;
	}

	public void setTotal(Float total) {
		this.total = total;
	}

}
